"""
V2 copy: структурированные константы для пользовательских текстов V2 (RU).
Переиспользует src.bot.messages.get_copy(), но добавляет структурированные константы.
"""
from src.bot.messages import get_copy


def t(copy_id: str) -> str:
    """Fetch copy by id from messages."""
    return get_copy(copy_id)


def fmt(copy_id: str, **kwargs: object) -> str:
    """Fetch copy and format with kwargs."""
    return t(copy_id).format(**kwargs)


# ---- Common copy ids (module-level for new UI kit usage) ----
MENU_BUTTON = "V2_MENU_BTN"
MENU_HINT = "V2_MENU_HINT"
CABINET_GREETING = "V2_CABINET_GREETING"
CABINET_STATUS = "V2_CABINET_STATUS"
MENU_STATUS_NO_PROJECT = "V2_MENU_STATUS_NO_PROJECT"
MENU_RESTART_CONFIRM = "V2_MENU_RESTART_CONFIRM"
MENU_CONTINUE = "V2_MENU_CONTINUE"
MENU_CURRENT_STEP = "V2_MENU_CURRENT_STEP"
MENU_PROJECT = "V2_MENU_PROJECT"
MENU_RESTART = "V2_MENU_RESTART"
MENU_MY_PROJECTS = "V2_MENU_MY_PROJECTS"
MENU_CREATE = "V2_MENU_CREATE"
MENU_HELP = "V2_MENU_HELP"

BTN_RESUME_PROJECT = "V2_BTN_RESUME_PROJECT"
BTN_CREATE_PROJECT = "V2_BTN_CREATE_PROJECT"
BTN_MY_PROJECTS = "V2_BTN_MY_PROJECTS"
BTN_HOW_IT_WORKS = "V2_BTN_HOW_IT_WORKS"

MY_PROJECTS_HEADER = "V2_MY_PROJECTS_HEADER"
MY_PROJECTS_EMPTY = "V2_MY_PROJECTS_EMPTY"
BTN_OPEN = "V2_BTN_OPEN"

HELP_TEXT = "V2_HELP_TEXT"
HOW_IT_WORKS = "V2_HOW_IT_WORKS"
PROJECT_NO_DATA = "V2_PROJECT_NO_DATA"

STATUS_DRAFT = "V2_STATUS_DRAFT"
STATUS_PENDING = "V2_STATUS_PENDING"
STATUS_NEEDS_FIX = "V2_STATUS_NEEDS_FIX"
STATUS_APPROVED = "V2_STATUS_APPROVED"
STATUS_REJECTED = "V2_STATUS_REJECTED"

BTN_BACK = "V2_BTN_BACK"
BTN_SKIP = "V2_BTN_SKIP"
BTN_FINISH_LINKS = "V2_FINISH_LINKS"
BTN_SAVE = "V2_SAVE_BTN"
SAVED_RESUME = "V2_SAVED_RESUME"
LINK_ADDED = "V2_LINK_ADDED"
INVALID_REQUIRED = "V2_INVALID_REQUIRED"
INVALID_EMAIL = "V2_INVALID_EMAIL"
INVALID_LINK = "V2_INVALID_LINK"
INVALID_TIME = "V2_INVALID_TIME"
INVALID_COST = "V2_INVALID_COST"
INVALID_BUDGET = "V2_INVALID_BUDGET"

BTN_SUBMIT_TO_MODERATION = "BTN_SUBMIT_TO_MODERATION"
BTN_EDIT_ANSWERS = "BTN_EDIT_ANSWERS"
BTN_YES_SEND = "BTN_YES_SEND"
BTN_NO_RETURN = "BTN_NO_RETURN"
YES_BUTTON = "YES_BUTTON"
NO_BUTTON = "NO_BUTTON"
SUBMIT_PROMPT = "SUBMIT_Q7_SEND_PROMPT"
SUBMIT_CONFIRM = "V2_SUBMIT_CONFIRM"
ADMIN_CHAT_MISSING = "V2_ADMIN_CHAT_MISSING"
ERROR_MODERATION_SEND = "ERROR_MODERATION_SEND"

MOD_NO_RIGHTS = "V2_MOD_NO_RIGHTS"
MOD_ALREADY = "V2_MOD_ALREADY"
MOD_APPROVE_USER = "V2_MOD_APPROVE_USER"
MOD_NEEDS_FIX_USER = "V2_MOD_NEEDS_FIX_USER"
MOD_REJECT_USER = "V2_MOD_REJECT_USER"
MOD_ASK_FIX = "V2_MOD_ASK_FIX"
MOD_ASK_REJECT = "V2_MOD_ASK_REJECT"
MOD_APPROVED_LABEL = "V2_MOD_APPROVED_LABEL"
MOD_NEEDS_FIX_LABEL = "V2_MOD_NEEDS_FIX_LABEL"
MOD_REJECTED_LABEL = "V2_MOD_REJECTED_LABEL"
BTN_MAKE_EDIT = "BTN_MAKE_EDIT"

BTN_DELETE = "V2_BTN_DELETE"
DELETE_CONFIRM = "V2_DELETE_CONFIRM"
DELETED = "V2_DELETED"
DELETE_CANCELLED = "V2_DELETE_CANCELLED"

UNKNOWN_BUTTON = "V2_UNKNOWN_BUTTON"

CARD_EMPTY_VALUE = "—"
UNTITLED_PROJECT = "Без названия"
OPEN_BUTTON_TEMPLATE = "{label} ({title})"


class V2Copy:
    """Структурированные константы для V2 copy ID."""
    
    # Навигация
    BTN_BACK = "V2_BTN_BACK"
    BTN_SKIP = "V2_BTN_SKIP"
    BTN_SAVE = "V2_SAVE_BTN"
    BTN_MENU = "V2_MENU_BTN"
    BTN_FINISH_LINKS = "V2_FINISH_LINKS"
    
    # Кабинет
    CABINET_GREETING = "V2_CABINET_GREETING"
    CABINET_STATUS = "V2_CABINET_STATUS"
    MENU_HINT = "V2_MENU_HINT"
    MENU_CONTINUE = "V2_MENU_CONTINUE"
    MENU_CONTINUE_WIZARD = "V2_MENU_CONTINUE_WIZARD"
    MENU_CURRENT_STEP = "V2_MENU_CURRENT_STEP"
    MENU_PROJECT = "V2_MENU_PROJECT"
    MENU_RESTART = "V2_MENU_RESTART"
    MENU_MY_PROJECTS = "V2_MENU_MY_PROJECTS"
    MENU_CREATE = "V2_MENU_CREATE"
    MENU_HELP = "V2_MENU_HELP"
    MENU_RESTART_CONFIRM = "V2_MENU_RESTART_CONFIRM"
    MENU_STATUS_NO_PROJECT = "V2_MENU_STATUS_NO_PROJECT"
    MENU_PREVIEW = "V2_MENU_PREVIEW"
    MENU_DRAFTS = "V2_MENU_DRAFTS"
    MENU_PUBLICATIONS = "V2_MENU_PUBLICATIONS"
    MENU_SETTINGS = "V2_MENU_SETTINGS"
    MENU_HELP_BTN = "V2_MENU_HELP_BTN"
    MENU_BACK = "V2_MENU_BACK"
    
    # Превью
    PREVIEW_HEADER = "V2_PREVIEW_POST"
    PREVIEW_SUBMIT_CONFIRM = "SUBMIT_Q7_SEND_PROMPT"
    PREVIEW_SUCCESS = "V2_SUBMIT_CONFIRM"
    BTN_SUBMIT_TO_MODERATION = "BTN_SUBMIT_TO_MODERATION"
    BTN_EDIT_ANSWERS = "BTN_EDIT_ANSWERS"
    BTN_YES_SEND = "BTN_YES_SEND"
    BTN_NO_RETURN = "BTN_NO_RETURN"
    
    # Ошибки
    ERROR_REQUIRED = "V2_INVALID_REQUIRED"
    ERROR_EMAIL = "V2_INVALID_EMAIL"
    ERROR_LINK = "V2_INVALID_LINK"
    ERROR_TIME = "V2_INVALID_TIME"
    ERROR_COST = "V2_INVALID_COST"
    ERROR_BUDGET = "V2_INVALID_BUDGET"
    
    # Модерация
    MOD_APPROVE_USER = "V2_MOD_APPROVE_USER"
    MOD_NEEDS_FIX_USER = "V2_MOD_NEEDS_FIX_USER"
    MOD_REJECT_USER = "V2_MOD_REJECT_USER"
    MOD_ASK_FIX = "V2_MOD_ASK_FIX"
    MOD_ASK_REJECT = "V2_MOD_ASK_REJECT"
    BTN_MAKE_EDIT = "BTN_MAKE_EDIT"
    
    # Проект
    PROJECT_NO_DATA = "V2_PROJECT_NO_DATA"
    MY_PROJECTS_HEADER = "V2_MY_PROJECTS_HEADER"
    MY_PROJECTS_EMPTY = "V2_MY_PROJECTS_EMPTY"
    BTN_OPEN = "V2_BTN_OPEN"
    
    # Статусы
    STATUS_DRAFT = "V2_STATUS_DRAFT"
    STATUS_PENDING = "V2_STATUS_PENDING"
    STATUS_NEEDS_FIX = "V2_STATUS_NEEDS_FIX"
    STATUS_APPROVED = "V2_STATUS_APPROVED"
    STATUS_REJECTED = "V2_STATUS_REJECTED"
    
    # Удаление
    BTN_DELETE = "V2_BTN_DELETE"
    DELETE_CONFIRM = "V2_DELETE_CONFIRM"
    DELETED = "V2_DELETED"
    DELETE_CANCELLED = "V2_DELETE_CANCELLED"
    
    # Прочее
    SAVED_RESUME = "V2_SAVED_RESUME"
    LINK_ADDED = "V2_LINK_ADDED"
    YES_BUTTON = "YES_BUTTON"
    NO_BUTTON = "NO_BUTTON"
    UNKNOWN_BUTTON = "V2_UNKNOWN_BUTTON"
    
    @staticmethod
    def get(key: str) -> str:
        """Обёртка над get_copy() для удобства."""
        return get_copy(key)
